// Walks the contentEditable letter DOM (the same #LETTER_DOM_ID the PDF
// export captures) and emits a .docx Blob via the `docx` package. The
// guarantee: any edits the user made in the browser flow through to the
// downloaded file, exactly as they flow through to the PDF.
//
// Mapping:
//   h1, h2, h3       -> HeadingLevel.HEADING_{1,2,3}
//   p                -> body paragraph; inline strong / em / a are preserved
//   ul / ol          -> bullet / numbered list (one level deep; nested lists
//                       collapse to the outer level on purpose; lawyers
//                       redline flat)
//   hr               -> horizontal rule via a single empty paragraph with a
//                       bottom border
//
// Everything else is rendered as plain body text. This is deliberate: the
// letter is a legal document, not an HTML page; restricting the surface
// keeps the docx clean for redline in Word.

import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
  type ParagraphChild,
} from "docx";

type Run = TextRun;

const PARAGRAPH_TAGS = new Set(["P", "DIV"]);
const HEADING_LEVEL_BY_TAG: Record<string, (typeof HeadingLevel)[keyof typeof HeadingLevel]> = {
  H1: HeadingLevel.HEADING_1,
  H2: HeadingLevel.HEADING_2,
  H3: HeadingLevel.HEADING_3,
};

/**
 * Convert the live DOM rooted at `root` into a docx Blob.
 *
 * Pure function modulo `document` access through `root`; tests can pass a
 * JSDOM-built element and assert against the returned Blob's bytes.
 */
export async function letterToDocx(root: HTMLElement): Promise<Blob> {
  const paragraphs: Paragraph[] = [];
  walk(root, paragraphs, { bold: false, italic: false });

  if (paragraphs.length === 0) {
    paragraphs.push(new Paragraph({ children: [new TextRun("")] }));
  }

  const doc = new Document({
    creator: "Laytimely",
    title: "Demurrage claim letter",
    description: "Generated by Laytimely from the on-screen letter.",
    sections: [
      {
        properties: { page: { margin: { top: 720, bottom: 720, left: 720, right: 720 } } },
        children: paragraphs,
      },
    ],
  });

  return Packer.toBlob(doc);
}

type Inheritance = { bold: boolean; italic: boolean };

function walk(node: Node, out: Paragraph[], inherit: Inheritance): void {
  if (!(node instanceof Element)) return;
  const tag = node.tagName;

  if (tag in HEADING_LEVEL_BY_TAG) {
    out.push(
      new Paragraph({
        heading: HEADING_LEVEL_BY_TAG[tag],
        children: inlineChildren(node, inherit),
      }),
    );
    return;
  }

  if (tag === "HR") {
    out.push(
      new Paragraph({
        children: [new TextRun("")],
        border: {
          bottom: { color: "999999", space: 1, style: BorderStyle.SINGLE, size: 6 },
        },
      }),
    );
    return;
  }

  if (tag === "UL" || tag === "OL") {
    const numbered = tag === "OL";
    for (const li of Array.from(node.children)) {
      if (li.tagName !== "LI") continue;
      out.push(
        new Paragraph({
          bullet: numbered ? undefined : { level: 0 },
          numbering: numbered ? { reference: "default", level: 0 } : undefined,
          children: inlineChildren(li, inherit),
        }),
      );
    }
    return;
  }

  if (PARAGRAPH_TAGS.has(tag)) {
    const children = inlineChildren(node, inherit);
    if (children.length > 0) {
      out.push(new Paragraph({ children, alignment: AlignmentType.LEFT }));
    }
    return;
  }

  // Anything else: recurse into children so nested wrappers do not eat the
  // body text.
  for (const child of Array.from(node.childNodes)) {
    walk(child, out, inherit);
  }
}

function inlineChildren(node: Node, inherit: Inheritance): Run[] {
  const runs: Run[] = [];
  collect(node, runs, inherit);
  return runs;
}

function collect(node: Node, runs: Run[], inherit: Inheritance): void {
  if (node.nodeType === Node.TEXT_NODE) {
    const text = (node.textContent ?? "").replace(/\s+/g, " ");
    if (text) runs.push(new TextRun({ text, bold: inherit.bold || undefined, italics: inherit.italic || undefined }));
    return;
  }
  if (!(node instanceof Element)) return;

  const tag = node.tagName;
  const next: Inheritance = {
    bold: inherit.bold || tag === "STRONG" || tag === "B",
    italic: inherit.italic || tag === "EM" || tag === "I",
  };

  // Inline elements that do not produce their own paragraph: recurse into
  // their children with the updated inheritance. Block elements would have
  // been handled by `walk`; reaching them here from inside a paragraph means
  // the source markdown produced something unusual; flatten quietly.
  for (const child of Array.from(node.childNodes)) {
    collect(child, runs, next);
  }
}
