"""voyage_documents

Revision ID: 3e1ee1f39a0c
Revises: 77986f4b9f2d
Create Date: 2026-05-29 20:57:31.427303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1ee1f39a0c'
down_revision: Union[str, Sequence[str], None] = '77986f4b9f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voyage_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voyage_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.voyage_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voyage_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voyage_documents_voyage_id'), ['voyage_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voyage_documents_voyage_id'))

    op.drop_table('voyage_documents')
    # ### end Alembic commands ###
