"""initial schema

Revision ID: 77986f4b9f2d
Revises: 
Create Date: 2026-05-29 19:09:22.080014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77986f4b9f2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voyages',
    sa.Column('voyage_id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('perspective', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('voyage_id')
    )
    with op.batch_alter_table('voyages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voyages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_voyages_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('claim_packets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voyage_id', sa.String(), nullable=False),
    sa.Column('quantum_eur', sa.Float(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('dispute_narrative_markdown', sa.Text(), nullable=False),
    sa.Column('claim_letter_markdown', sa.Text(), nullable=False),
    sa.Column('time_bar_date', sa.String(), nullable=False),
    sa.Column('submitted_within_time_bar', sa.Boolean(), nullable=False),
    sa.Column('days_until_time_bar', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.voyage_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_packets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_packets_voyage_id'), ['voyage_id'], unique=True)

    op.create_table('dispute_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voyage_id', sa.String(), nullable=False),
    sa.Column('perspective', sa.String(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.voyage_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispute_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispute_analyses_voyage_id'), ['voyage_id'], unique=True)

    op.create_table('extractions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voyage_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.voyage_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extractions_voyage_id'), ['voyage_id'], unique=True)

    op.create_table('laytime_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voyage_id', sa.String(), nullable=False),
    sa.Column('laytime_allowed_hours', sa.Float(), nullable=False),
    sa.Column('laytime_used_hours', sa.Float(), nullable=False),
    sa.Column('time_on_demurrage_hours', sa.Float(), nullable=False),
    sa.Column('time_excepted_hours', sa.Float(), nullable=False),
    sa.Column('demurrage_rate_per_hour_eur', sa.Float(), nullable=False),
    sa.Column('demurrage_due_eur', sa.Float(), nullable=False),
    sa.Column('despatch_due_eur', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.voyage_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laytime_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laytime_results_voyage_id'), ['voyage_id'], unique=True)

    op.create_table('charter_parties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(), nullable=False),
    sa.Column('cp_date', sa.String(), nullable=False),
    sa.Column('vessel_name', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('charterer', sa.String(), nullable=False),
    sa.Column('load_port', sa.String(), nullable=False),
    sa.Column('discharge_port', sa.String(), nullable=False),
    sa.Column('laytime_allowed_hours', sa.Float(), nullable=False),
    sa.Column('laytime_basis', sa.String(), nullable=False),
    sa.Column('demurrage_rate_eur_per_day', sa.Float(), nullable=False),
    sa.Column('despatch_rate_eur_per_day', sa.Float(), nullable=True),
    sa.Column('nor_tender_window', sa.Text(), nullable=False),
    sa.Column('laytime_commencement_rule', sa.Text(), nullable=False),
    sa.Column('time_bar_days', sa.Integer(), nullable=True),
    sa.Column('time_bar_basis', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('charter_parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charter_parties_extraction_id'), ['extraction_id'], unique=True)

    op.create_table('claim_packet_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('packet_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['claim_packets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_packet_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_packet_documents_packet_id'), ['packet_id'], unique=False)

    op.create_table('dispute_narrative_paragraphs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispute_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['dispute_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispute_narrative_paragraphs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispute_narrative_paragraphs_dispute_id'), ['dispute_id'], unique=False)

    op.create_table('event_classifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('laytime_result_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('counts_against_laytime', sa.Boolean(), nullable=False),
    sa.Column('applicable_exception', sa.String(), nullable=True),
    sa.Column('clause_basis', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('contestable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['laytime_result_id'], ['laytime_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_classifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_classifications_laytime_result_id'), ['laytime_result_id'], unique=False)

    op.create_table('flagged_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispute_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('owner_argument', sa.Text(), nullable=False),
    sa.Column('charterer_argument', sa.Text(), nullable=False),
    sa.Column('owner_position_strength', sa.Float(), nullable=False),
    sa.Column('incremental_demurrage_eur', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['dispute_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flagged_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flagged_events_dispute_id'), ['dispute_id'], unique=False)

    op.create_table('laytime_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('laytime_result_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('from_ts', sa.String(), nullable=False),
    sa.Column('to_ts', sa.String(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('counts', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('running_total_hours', sa.Float(), nullable=False),
    sa.Column('event_id_start', sa.String(), nullable=False),
    sa.Column('event_id_end', sa.String(), nullable=False),
    sa.Column('contestable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['laytime_result_id'], ['laytime_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laytime_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laytime_rows_laytime_result_id'), ['laytime_result_id'], unique=False)

    op.create_table('notices_of_readiness',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('tendered_at', sa.String(), nullable=False),
    sa.Column('accepted_at', sa.String(), nullable=True),
    sa.Column('tendered_by', sa.String(), nullable=False),
    sa.Column('tendered_to', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('free_pratique_granted_at', sa.String(), nullable=True),
    sa.Column('berth_status_at_tender', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notices_of_readiness', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notices_of_readiness_extraction_id'), ['extraction_id'], unique=True)

    op.create_table('statements_of_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('port', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statements_of_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statements_of_facts_extraction_id'), ['extraction_id'], unique=True)

    op.create_table('clause_excerpts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('charter_party_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('clause_no', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['charter_party_id'], ['charter_parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clause_excerpts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clause_excerpts_charter_party_id'), ['charter_party_id'], unique=False)

    op.create_table('cp_exception_clauses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('charter_party_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['charter_party_id'], ['charter_parties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cp_exception_clauses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cp_exception_clauses_charter_party_id'), ['charter_party_id'], unique=False)

    op.create_table('flagged_event_clauses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flagged_event_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['flagged_event_id'], ['flagged_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flagged_event_clauses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flagged_event_clauses_flagged_event_id'), ['flagged_event_id'], unique=False)

    op.create_table('flagged_event_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flagged_event_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['flagged_event_id'], ['flagged_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flagged_event_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flagged_event_evidence_flagged_event_id'), ['flagged_event_id'], unique=False)

    op.create_table('sof_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sof_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sof_id'], ['statements_of_facts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sof_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sof_events_sof_id'), ['sof_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sof_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sof_events_sof_id'))

    op.drop_table('sof_events')
    with op.batch_alter_table('flagged_event_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flagged_event_evidence_flagged_event_id'))

    op.drop_table('flagged_event_evidence')
    with op.batch_alter_table('flagged_event_clauses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flagged_event_clauses_flagged_event_id'))

    op.drop_table('flagged_event_clauses')
    with op.batch_alter_table('cp_exception_clauses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cp_exception_clauses_charter_party_id'))

    op.drop_table('cp_exception_clauses')
    with op.batch_alter_table('clause_excerpts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clause_excerpts_charter_party_id'))

    op.drop_table('clause_excerpts')
    with op.batch_alter_table('statements_of_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statements_of_facts_extraction_id'))

    op.drop_table('statements_of_facts')
    with op.batch_alter_table('notices_of_readiness', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notices_of_readiness_extraction_id'))

    op.drop_table('notices_of_readiness')
    with op.batch_alter_table('laytime_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laytime_rows_laytime_result_id'))

    op.drop_table('laytime_rows')
    with op.batch_alter_table('flagged_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flagged_events_dispute_id'))

    op.drop_table('flagged_events')
    with op.batch_alter_table('event_classifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_classifications_laytime_result_id'))

    op.drop_table('event_classifications')
    with op.batch_alter_table('dispute_narrative_paragraphs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispute_narrative_paragraphs_dispute_id'))

    op.drop_table('dispute_narrative_paragraphs')
    with op.batch_alter_table('claim_packet_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_packet_documents_packet_id'))

    op.drop_table('claim_packet_documents')
    with op.batch_alter_table('charter_parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charter_parties_extraction_id'))

    op.drop_table('charter_parties')
    with op.batch_alter_table('laytime_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laytime_results_voyage_id'))

    op.drop_table('laytime_results')
    with op.batch_alter_table('extractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extractions_voyage_id'))

    op.drop_table('extractions')
    with op.batch_alter_table('dispute_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispute_analyses_voyage_id'))

    op.drop_table('dispute_analyses')
    with op.batch_alter_table('claim_packets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_packets_voyage_id'))

    op.drop_table('claim_packets')
    with op.batch_alter_table('voyages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voyages_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_voyages_created_at'))

    op.drop_table('voyages')
    op.drop_table('users')
    # ### end Alembic commands ###
