"""voyage_evidence

Revision ID: f555fafd0771
Revises: 3e1ee1f39a0c
Create Date: 2026-05-29 21:53:43.540856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f555fafd0771'
down_revision: Union[str, Sequence[str], None] = '3e1ee1f39a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voyage_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voyage_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('observed_value', sa.String(), nullable=False),
    sa.Column('supports', sa.String(), nullable=False),
    sa.Column('citation', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.voyage_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voyage_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voyage_evidence_voyage_id'), ['voyage_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyage_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voyage_evidence_voyage_id'))

    op.drop_table('voyage_evidence')
    # ### end Alembic commands ###
